sys:
  name: "springboot-study"
  userList:
    - userId: 1
      userName: "eugene1"
    - userId: 2
      userName: "eugene2"

eugene-by-annotation:
  man: true
  age: 11
  name: "avengerEug-by-annotation"

eugene-by-spring-factories:
  man: false
  age: 24
  name: "avengerEug-by-spring-factories"



