spring:
  redis:
    redisson:
      config: classpath:redisson-local.yaml

  datasource:
    url: jdbc:mysql://192.168.220.132/redisStudy?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

#########################
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.eugene.sumarry.springbootredis.model
  type-handlers-package: com.eugene.sumarry.springbootredis.typeHandler
  configuration:
    cache-enabled: true